version: 2.1

commands:
  verify-docker-compose-v1:
    steps:
      - run:
          name: Check if `docker-compose` is available
          command: |
            # uses || true to ensure this always passes
            docker-compose version || true

jobs:
  explore-docker-compose:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Verify Docker Compose V2 works
          command: |
            # Currently, Docker Compose V2 is available in cimg/base:stable.
            # As such, `docker compose` works.
            # https://docs.docker.com/compose/cli-command/
            docker compose version
      - verify-docker-compose-v1
      - run:
          name: Install Compose Switch (manually)
          command: |
            # https://docs.docker.com/compose/cli-command/#compose-switch
            sudo curl -fL https://github.com/docker/compose-switch/releases/download/v1.0.4/docker-compose-linux-amd64 -o /usr/local/bin/compose-switch
            sudo chmod +x /usr/local/bin/compose-switch
            sudo update-alternatives --install /usr/local/bin/docker-compose docker-compose /usr/local/bin/compose-switch 99
            
            # check
            which docker-compose
      - verify-docker-compose-v1

workflows:
  main:
    jobs:
      - explore-docker-compose
