version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run: |
          docker-compose --version
          # if V2, should be supported
          docker compose version
